<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OrderService.Infrastructure</AssemblyName>
    <RootNamespace>OrderService.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SaaSCommon.Infrastructure\SaaSCommon.Infrastructure.csproj" />
    <ProjectReference Include="..\OrderService.Application\OrderService.Application.csproj" />
    <ProjectReference Include="..\..\Payment\PaymentService.Contracts\PaymentService.Contracts.csproj" />
    <ProjectReference Include="..\..\Inventory\InventoryService.Contracts\InventoryService.Contracts.csproj" />
  </ItemGroup>
</Project>
