<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>NotificationService.Infrastructure</AssemblyName>
    <RootNamespace>NotificationService.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Quartz" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SaaSCommon.Infrastructure\SaaSCommon.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Identity\IdentityService.Contracts\IdentityService.Contracts.csproj" />
    <ProjectReference Include="..\NotificationService.Application\NotificationService.Application.csproj" />
    <ProjectReference Include="..\NotificationService.Domain\NotificationService.Domain.csproj" />
    <ProjectReference Include="..\NotificationService.Contracts\NotificationService.Contracts.csproj" />
  </ItemGroup>
</Project>
