apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: saas-platform
  labels:
    app: customer
spec:
  type: ClusterIP
  selector:
    app: customer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
