<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>InventoryService.Application</AssemblyName>
    <RootNamespace>InventoryService.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Quartz" />
    <PackageReference Include="Quartz.Extensions.Hosting" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SaaSCommon.Application\SaaSCommon.Application.csproj" />
    <ProjectReference Include="..\InventoryService.Domain\InventoryService.Domain.csproj" />
    <ProjectReference Include="..\InventoryService.Contracts\InventoryService.Contracts.csproj" />
  </ItemGroup>
</Project>
