<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>IdentityService.Application</AssemblyName>
    <RootNamespace>IdentityService.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SaaSCommon.Domain\SaaSCommon.Domain.csproj" />
    <ProjectReference Include="..\..\Shared\SaaSCommon.Application\SaaSCommon.Application.csproj" />
    <ProjectReference Include="..\IdentityService.Domain\IdentityService.Domain.csproj" />
    <ProjectReference Include="..\IdentityService.Contracts\IdentityService.Contracts.csproj" />
  </ItemGroup>
</Project>
