<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CustomerService.Contracts</AssemblyName>
    <RootNamespace>CustomerService.Contracts</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SaaSCommon.Domain\SaaSCommon.Domain.csproj" />
  </ItemGroup>
</Project>
