apiVersion: v1
kind: Service
metadata:
  name: inventory
  namespace: saas-platform
  labels:
    app: inventory
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
