apiVersion: v1
kind: Service
metadata:
  name: tenant
  namespace: saas-platform
  labels:
    app: tenant
spec:
  type: ClusterIP
  selector:
    app: tenant
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
