<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TenantService.Infrastructure</AssemblyName>
    <RootNamespace>TenantService.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SaaSCommon.Infrastructure\SaaSCommon.Infrastructure.csproj" />
    <ProjectReference Include="..\TenantService.Application\TenantService.Application.csproj" />
  </ItemGroup>
</Project>
